### ISSUE TITLE
Add latin-extended charset support for default fonts

### ISSUE THREAD

**Issue by abbaselmas** [pixelgrade/gema-lite#23]
Latin extended characters (i think) are note supported in lite version. Is it possible to choose a font that supports latin extended characters on the lite version? Characters that i have encountered problems are "ş Ş İ ğ Ğ"
![gema](https://user-images.githubusercontent.com/28142617/61439533-5e859e80-a94a-11e9-8f58-1d59f655aeb4.JPG)

**Comment by georgeolaru** [comment]
@abbaselmas I checked the font and it seems that in the latest version of [Montserrat](https://fonts.google.com/specimen/Montserrat?selection.family=Montserrat) there is support for the latin-extended charset. 🤞

We can either replace the font files inside the theme with the newest ones (see this zip file: [Montserrat.zip](https://github.com/pixelgrade/gema-lite/files/3409733/Montserrat.zip)) or load them directly from Google Fonts (as we do in [other](https://github.com/pixelgrade/julia-lite/blob/be71f5670d418f289e7c7c1b0b6c301269eb6cd2/inc/extras.php) themes and in the Pro version).

@BurloiuCosmin @madalingorbanescu When you have time, please take a look.

**Comment by madalingorbanescu** [comment]
@georgeolaru I chose to load it directly from Google Fonts because, in that way, the fonts will always be at the latest version.
